Repository Team-Ampersand/GYMI-Android, pull requests merged in 2023-08, with the labels that each got.

#32 🔀 :: (#31) add dependency for gus
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/Versions.kt
  presentation/build.gradle.kts
Labels: setting

#34 🔀 :: (#33) refactoring for gus
  .gitignore
  app/.gitignore
  buildSrc/src/main/java/Versions.kt
  data/.gitignore
  domain/.gitignore
  presentation/.gitignore
  presentation/src/main/java/com/mpersand/presentation/view/login/LoginScreen.kt
  presentation/src/main/res/drawable/ic_gymi.xml
Labels: feature

#38 🔀 :: (#37) court modal component
  .gitignore
  .idea/.gitignore
  .idea/.name
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/kotlinc.xml
  .idea/misc.xml
  .idea/vcs.xml
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/Versions.kt
  presentation/build.gradle.kts
  presentation/src/main/java/com/mpersand/presentation/view/component/CourtModal.kt
Labels: publishing

#40 🔀 :: (#39) equipment modal component
  presentation/src/main/java/com/mpersand/presentation/view/component/EquipmentModal.kt
Labels: publishing

#43 🔀 :: (#41) profile page publishing
  buildSrc/src/main/java/Versions.kt
  presentation/src/main/java/com/mpersand/presentation/view/profile/ProfileScreen.kt
Labels: publishing

#44 🔀 :: (#42) use gymi button instead material button
  presentation/src/main/java/com/mpersand/presentation/view/component/CourtModal.kt
  presentation/src/main/java/com/mpersand/presentation/view/component/EquipmentModal.kt
Labels: publishing

#45 🔀 :: (#35) main page publishing
  presentation/src/main/java/com/mpersand/presentation/view/main/MainScreen.kt
Labels: publishing

#48 🔀 :: (#47) report modal component
  buildSrc/src/main/java/Versions.kt
  presentation/src/main/java/com/mpersand/presentation/view/component/ReportModal.kt
Labels: publishing

#50 🔀 :: (#49) add bw color
  buildSrc/src/main/java/Versions.kt
  presentation/src/main/java/com/mpersand/presentation/view/component/CourtModal.kt
  presentation/src/main/java/com/mpersand/presentation/view/component/EquipmentModal.kt
  presentation/src/main/java/com/mpersand/presentation/view/component/ReportModal.kt
  presentation/src/main/java/com/mpersand/presentation/view/main/MainScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/profile/ProfileScreen.kt
Labels: publishing

#56 🔀 :: (#55) notice list page publishing
  presentation/src/main/java/com/mpersand/presentation/view/notice/list/NoticeListScreen.kt
Labels: publishing

#53 🔀 :: (#52) use design system to login
  presentation/src/main/java/com/mpersand/presentation/view/login/LoginScreen.kt
Labels: publishing

#58 🔀 :: (#57) notice write page publishing
  presentation/src/main/java/com/mpersand/presentation/view/notice/write/NoticeWriteScreen.kt
Labels: publishing

#60 🔀 :: (#47) equipment page publishing
  presentation/src/main/java/com/mpersand/presentation/view/equipment/EquipmentScreen.kt
Labels: publishing

#61 🔀 :: (#59) notice empty page publishing
  presentation/src/main/java/com/mpersand/presentation/view/notice/empty/NoticeEmptyScreen.kt
Labels: publishing

#63 🔀 :: (#62) notice detail page publishing
  presentation/src/main/java/com/mpersand/presentation/view/notice/detail/NoticeDetailScreen.kt
Labels: publishing

#65 🔀 :: (#64) notice edit page publishing
  presentation/src/main/java/com/mpersand/presentation/view/notice/edit/NoticeEditScreen.kt
Labels: publishing

#67 🔀 :: (#66) modifier gymi badminton court for main page
  buildSrc/src/main/java/Versions.kt
  presentation/src/main/java/com/mpersand/presentation/view/component/BadmintonHalfCourt.kt
  presentation/src/main/java/com/mpersand/presentation/view/main/MainScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/reservation/ReservationScreen.kt
Labels: publishing

#71 🔀 :: (#69) write navigation logic
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mpersand/gymi_android/GYMINavHost.kt
  app/src/main/java/com/mpersand/gymi_android/MainActivity.kt
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/Versions.kt
  presentation/build.gradle.kts
  presentation/src/main/java/com/mpersand/presentation/view/equipment/EquipmentScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/equipment/navigation/EquipmentNavigation.kt
  presentation/src/main/java/com/mpersand/presentation/view/login/navigation/LoginNavigation.kt
  presentation/src/main/java/com/mpersand/presentation/view/main/MainScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/main/navigation/MainNavigation.kt
  presentation/src/main/java/com/mpersand/presentation/view/notice/detail/NoticeDetailScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/notice/detail/navigation/NoticeDetailNavigation.kt
  presentation/src/main/java/com/mpersand/presentation/view/notice/edit/NoticeEditScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/notice/edit/navigation/NoticeEditNavigation.kt
  presentation/src/main/java/com/mpersand/presentation/view/notice/empty/NoticeEmptyScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/notice/empty/navigation/NoticeEmptyNavigation.kt
  presentation/src/main/java/com/mpersand/presentation/view/notice/list/NoticeListScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/notice/list/navigation/NoticeListNavigation.kt
  presentation/src/main/java/com/mpersand/presentation/view/notice/write/NoticeWriteScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/notice/write/navigation/NoticeWriteNavigation.kt
  presentation/src/main/java/com/mpersand/presentation/view/profile/ProfileScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/profile/navigation/ProfileNavigation.kt
  presentation/src/main/java/com/mpersand/presentation/view/reservation/ReservationScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/reservation/navigation/ReservationNavigation.kt
Labels: feature

#73 🔀 :: (#72) set gymi theme light or dark
  app/src/main/java/com/mpersand/gymi_android/MainActivity.kt
  presentation/src/main/java/com/mpersand/presentation/view/login/LoginScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/notice/detail/NoticeDetailScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/notice/edit/NoticeEditScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/notice/empty/NoticeEmptyScreen.kt
Labels: publishing

#75 🔀 :: (#74) write navigation backstack logic
  app/src/main/java/com/mpersand/gymi_android/MainActivity.kt
  app/src/main/java/com/mpersand/gymi_android/navigation/GYMINavHost.kt
  app/src/main/java/com/mpersand/gymi_android/navigation/GYMINavigation.kt
  presentation/src/main/java/com/mpersand/presentation/view/main/navigation/MainNavigation.kt
Labels: feature

#77 🔀 :: (#76) create version catalog
  app/build.gradle.kts
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/ProjectProperties.kt
  buildSrc/src/main/java/Versions.kt
  data/build.gradle.kts
  design_system/.gitignore
  design_system/build.gradle.kts
  design_system/consumer-rules.pro
  design_system/proguard-rules.pro
  design_system/src/androidTest/java/com/mpersand/design_system/ExampleInstrumentedTest.kt
  design_system/src/main/AndroidManifest.xml
  design_system/src/test/java/com/mpersand/design_system/ExampleUnitTest.kt
  domain/build.gradle.kts
  gradle/libs.versions.toml
  presentation/build.gradle.kts
  settings.gradle.kts
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#80 🔀 :: (#79) change app icon
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/ic_launcher_background.xml
Labels: 1️⃣ Priority: High, 🎨 Type: Publishing

#81 🔀 :: (#78) add gauth webview
  app/src/main/java/com/mpersand/gymi_android/MainActivity.kt
  app/src/main/java/com/mpersand/gymi_android/navigation/GYMINavHost.kt
  gradle/libs.versions.toml
  presentation/build.gradle.kts
  presentation/src/main/java/com/mpersand/presentation/view/login/LoginScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/login/navigation/LoginNavigation.kt
  presentation/src/main/java/com/mpersand/presentation/viewmodel/AuthViewModel.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#83 🔀 :: (#82) restriction modal component
  presentation/src/main/java/com/mpersand/presentation/view/component/RestrictionModal.kt
Labels: 1️⃣ Priority: High, 🎨 Type: Publishing

#85 🔀 :: (#84) refactoring for gus
  app/src/main/java/com/mpersand/gymi_android/MainActivity.kt
  presentation/src/main/java/com/mpersand/presentation/view/component/ReportModal.kt
  presentation/src/main/java/com/mpersand/presentation/view/component/RestrictionModal.kt
  presentation/src/main/java/com/mpersand/presentation/view/notice/edit/NoticeEditScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/notice/write/NoticeWriteScreen.kt
Labels: 1️⃣ Priority: High, 🔨 Type: Refector

#87 🔀 :: (#86) report list page publishing
  presentation/src/main/java/com/mpersand/presentation/view/report/list/ReportListScreen.kt
Labels: 1️⃣ Priority: High, 🎨 Type: Publishing

#89 🔀 :: (#88) report detail page publishing
  presentation/src/main/java/com/mpersand/presentation/view/report/detail/ReportDetailScreen.kt
Labels: 1️⃣ Priority: High, 🎨 Type: Publishing

#91 🔀 :: (#90) restrict list page publishing
  presentation/src/main/java/com/mpersand/presentation/view/restrict/RestrictListScreen.kt
Labels: 1️⃣ Priority: High, 🎨 Type: Publishing

#95 🔀 :: (#94) Feature - migrate json serialization gson to moshi
  app/build.gradle.kts
  app/src/main/java/com/mpersand/gymi_android/module/NetworkModule.kt
  data/build.gradle.kts
  data/src/main/java/com/mpersand/data/remote/model/auth/gAuthLogin/request/GauthLoginRequest.kt
  data/src/main/java/com/mpersand/data/remote/model/auth/gAuthLogin/response/GauthLoginResponse.kt
  data/src/main/java/com/mpersand/data/remote/model/auth/tokenReissue/request/TokenReissueRequest.kt
  data/src/main/java/com/mpersand/data/remote/network/AuthApi.kt
  data/src/main/java/com/mpersand/data/remote/util/RequestInterceptor.kt
  gradle/libs.versions.toml
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#97 🔀 :: (#96) migrate from kapt to ksp
  app/build.gradle.kts
  build.gradle.kts
  data/build.gradle.kts
  domain/build.gradle.kts
  gradle/libs.versions.toml
  presentation/build.gradle.kts
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#99 🔀 :: (#98) write declaration remote logic
  app/src/main/java/com/mpersand/gymi_android/module/NetworkModule.kt
  data/src/main/java/com/mpersand/data/remote/model/declaration/request/DeclarationRequest.kt
  data/src/main/java/com/mpersand/data/remote/model/declaration/response/DeclarationResponse.kt
  data/src/main/java/com/mpersand/data/remote/model/declaration/util/DeclarationType.kt
  data/src/main/java/com/mpersand/data/remote/network/DeclarationApi.kt
Labels: 1️⃣ Priority: High, 📬 Type: API

#102 🔀 :: (#100) write declaration data logic
  app/src/main/java/com/mpersand/gymi_android/module/RemoteDataSourceModule.kt
  data/build.gradle.kts
  data/src/main/java/com/mpersand/data/remote/datasource/declaration/DeclarationDataSource.kt
  data/src/main/java/com/mpersand/data/remote/datasource/declaration/DeclarationDataSourceImpl.kt
  data/src/test/java/com/mpersand/data/ExampleUnitTest.kt
  data/src/test/java/com/mpersand/data/network/declaration/FakeDeclarationApi.kt
  data/src/test/java/com/mpersand/data/remote/datasource/declaration/DeclarationDataSourceTest.kt
  gradle/libs.versions.toml
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#104 🔀 :: (#101) write notice remote logic
  app/src/main/java/com/mpersand/gymi_android/module/NetworkModule.kt
  data/src/main/java/com/mpersand/data/remote/model/notice/response/NoticeDetailResponse.kt
  data/src/main/java/com/mpersand/data/remote/model/notice/response/NoticeFile.kt
  data/src/main/java/com/mpersand/data/remote/model/notice/response/NoticeList.kt
  data/src/main/java/com/mpersand/data/remote/model/notice/response/NoticeResponse.kt
  data/src/main/java/com/mpersand/data/remote/network/NoticeApi.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#105 🔀 :: (#103) write declaration domain logic
  app/src/main/java/com/mpersand/gymi_android/module/RepositoryModule.kt
  data/src/main/java/com/mpersand/data/remote/model/declaration/request/DeclarationRequest.kt
  data/src/main/java/com/mpersand/data/remote/model/declaration/response/DeclarationResponse.kt
  data/src/main/java/com/mpersand/data/repository/DeclarationRepositoryImpl.kt
  data/src/test/java/com/mpersand/data/repository/DeclarationRepositoryTest.kt
  data/src/test/java/com/mpersand/data/repository/FakeDeclarationDataSource.kt
  domain/build.gradle.kts
  domain/src/main/java/com/mpersand/domain/model/declaration/request/DeclarationRequestModel.kt
  domain/src/main/java/com/mpersand/domain/model/declaration/response/DeclarationResponseModel.kt
  domain/src/main/java/com/mpersand/domain/model/declaration/util/DeclarationTypeModel.kt
  domain/src/main/java/com/mpersand/domain/repository/DeclarationRepository.kt
  domain/src/main/java/com/mpersand/domain/usecase/declaration/GetAllDeclarationsUseCase.kt
  domain/src/main/java/com/mpersand/domain/usecase/declaration/GetDeclarationByIdUseCase.kt
  domain/src/main/java/com/mpersand/domain/usecase/declaration/SubmitDeclarationUseCase.kt
  domain/src/test/java/com/mpersand/domain/ExampleUnitTest.kt
  domain/src/test/java/com/mpersand/domain/repository/FakeDeclarationRepository.kt
  domain/src/test/java/com/mpersand/domain/usecase/declaration/GetAllDeclarationsUseCaseTest.kt
  domain/src/test/java/com/mpersand/domain/usecase/declaration/GetDeclarationByIdUseCaseTest.kt
  domain/src/test/java/com/mpersand/domain/usecase/declaration/SubmitDeclarationUseCaseTest.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#108 🔀 :: (#107) foldering by feature
  app/src/main/java/com/mpersand/gymi_android/module/RemoteDataSourceModule.kt
  data/src/main/java/com/mpersand/data/remote/datasource/AuthDataSource.kt
  data/src/main/java/com/mpersand/data/remote/datasource/auth/AuthDataSource.kt
  data/src/main/java/com/mpersand/data/remote/datasource/auth/AuthDataSourceImpl.kt
  data/src/main/java/com/mpersand/data/remote/model/auth/request/GauthLoginRequest.kt
  data/src/main/java/com/mpersand/data/remote/model/auth/request/TokenReissueRequest.kt
  data/src/main/java/com/mpersand/data/remote/model/auth/response/GauthLoginResponse.kt
  data/src/main/java/com/mpersand/data/remote/network/AuthApi.kt
  data/src/main/java/com/mpersand/data/remote/util/RequestInterceptor.kt
  data/src/main/java/com/mpersand/data/repository/AuthRepositoryImpl.kt
  domain/src/main/java/com/mpersand/domain/usecase/auth/GauthLoginUseCase.kt
  domain/src/main/java/com/mpersand/domain/usecase/auth/GauthLogoutUseCase.kt
  domain/src/main/java/com/mpersand/domain/usecase/auth/SaveTokenUseCase.kt
  presentation/src/main/java/com/mpersand/presentation/view/login/LoginScreen.kt
  presentation/src/main/java/com/mpersand/presentation/viewmodel/auth/AuthViewModel.kt
Labels: 2️⃣ Priortiy: Medium, ⚡Type: Simple

#109 🔀 :: (#106) write declaration viewmodel logic
  presentation/src/main/java/com/mpersand/presentation/viewmodel/main/MainViewModel.kt
  presentation/src/main/java/com/mpersand/presentation/viewmodel/report/detail/ReportDetailViewModel.kt
  presentation/src/main/java/com/mpersand/presentation/viewmodel/report/list/ReportListViewModel.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature
