Repository Team-Ampersand/GYMI-Android, pull requests merged in 2023-09, with the labels that each got.

#112 🔀 :: (#110) write weekday court change logic
  presentation/src/main/java/com/mpersand/presentation/util/DayOfWeekType.kt
  presentation/src/main/java/com/mpersand/presentation/util/GetDayOfWeekType.kt
  presentation/src/main/java/com/mpersand/presentation/view/main/MainScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/reservation/ReservationScreen.kt
Labels: 1️⃣ Priority: High, ⚡Type: Simple

#113 🔀 :: (#111) write notice data logic
  app/src/main/java/com/mpersand/gymi_android/module/RemoteDataSourceModule.kt
  data/src/main/java/com/mpersand/data/remote/datasource/notice/NoticeDataSource.kt
  data/src/main/java/com/mpersand/data/remote/datasource/notice/NoticeDataSourceImpl.kt
  data/src/main/java/com/mpersand/data/remote/model/notice/response/NoticeList.kt
  data/src/main/java/com/mpersand/data/remote/model/notice/response/NoticeResponse.kt
  data/src/main/java/com/mpersand/data/remote/network/NoticeApi.kt
  data/src/test/java/com/mpersand/data/network/notice/FakeNoticeApi.kt
  data/src/test/java/com/mpersand/data/remote/datasource/notice/NoticeDataSourceTest.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#117 🔀 :: (#116) modify submit declaration parameter
  .github/workflows/android.yml
  data/src/main/java/com/mpersand/data/remote/datasource/declaration/DeclarationDataSource.kt
  data/src/main/java/com/mpersand/data/remote/datasource/declaration/DeclarationDataSourceImpl.kt
  data/src/main/java/com/mpersand/data/remote/network/DeclarationApi.kt
  data/src/main/java/com/mpersand/data/repository/DeclarationRepositoryImpl.kt
  data/src/test/java/com/mpersand/data/network/declaration/FakeDeclarationApi.kt
  data/src/test/java/com/mpersand/data/remote/datasource/declaration/DeclarationDataSourceTest.kt
  data/src/test/java/com/mpersand/data/repository/DeclarationRepositoryTest.kt
  data/src/test/java/com/mpersand/data/repository/FakeDeclarationDataSource.kt
  domain/src/main/java/com/mpersand/domain/repository/DeclarationRepository.kt
  domain/src/main/java/com/mpersand/domain/usecase/declaration/SubmitDeclarationUseCase.kt
  domain/src/test/java/com/mpersand/domain/repository/FakeDeclarationRepository.kt
  domain/src/test/java/com/mpersand/domain/usecase/declaration/SubmitDeclarationUseCaseTest.kt
  presentation/src/main/java/com/mpersand/presentation/viewmodel/main/MainViewModel.kt
Labels: 0️⃣ Priority: Critical, 📬 Type: API

#120 🔀 :: (#119) write court remote logic
  app/src/main/java/com/mpersand/gymi_android/module/NetworkModule.kt
  data/src/main/java/com/mpersand/data/remote/model/court/response/CourtResponse.kt
  data/src/main/java/com/mpersand/data/remote/model/util/CourtType.kt
  data/src/main/java/com/mpersand/data/remote/model/util/DayOfWeekType.kt
  data/src/main/java/com/mpersand/data/remote/model/util/SportType.kt
  data/src/main/java/com/mpersand/data/remote/network/CourtApi.kt
Labels: 1️⃣ Priority: High, 📬 Type: API

#122 🔀 :: (#118) write notice domain logic
  app/src/main/java/com/mpersand/gymi_android/module/RepositoryModule.kt
  data/src/main/java/com/mpersand/data/remote/model/notice/response/NoticeDetailResponse.kt
  data/src/main/java/com/mpersand/data/remote/model/notice/response/NoticeFile.kt
  data/src/main/java/com/mpersand/data/remote/model/notice/response/NoticeResponse.kt
  data/src/main/java/com/mpersand/data/repository/NoticeRepositoryImpl.kt
  data/src/test/java/com/mpersand/data/remote/datasource/notice/NoticeDataSourceTest.kt
  domain/build.gradle.kts
  domain/src/main/java/com/mpersand/domain/model/notice/response/NoticeDetailResponseModel.kt
  domain/src/main/java/com/mpersand/domain/model/notice/response/NoticeFileModel.kt
  domain/src/main/java/com/mpersand/domain/model/notice/response/NoticeResponseModel.kt
  domain/src/main/java/com/mpersand/domain/repository/NoticeRepository.kt
  domain/src/main/java/com/mpersand/domain/usecase/notice/CreateNoticeUseCase.kt
  domain/src/main/java/com/mpersand/domain/usecase/notice/DeleteNoticeUseCase.kt
  domain/src/main/java/com/mpersand/domain/usecase/notice/GetAllNoticeUseCase.kt
  domain/src/main/java/com/mpersand/domain/usecase/notice/GetDetailNoticeUsecase.kt
  domain/src/main/java/com/mpersand/domain/usecase/notice/ModifyNoticeUseCase.kt
  domain/src/test/java/com/mpersand/domain/repository/FakeNoticeRepository.kt
  domain/src/test/java/com/mpersand/domain/usecase/notice/CreateNoticeUseCaseTest.kt
  domain/src/test/java/com/mpersand/domain/usecase/notice/DeleteNoticeUseCaseTest.kt
  domain/src/test/java/com/mpersand/domain/usecase/notice/GetAllNoticeUseCaseTest.kt
  domain/src/test/java/com/mpersand/domain/usecase/notice/GetDetailNoticeUseCaseTest.kt
  domain/src/test/java/com/mpersand/domain/usecase/notice/ModifyNoticeUseCaseTest.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#124 🔀 :: (#121) write court data logic
  data/build.gradle.kts
  data/src/main/java/com/mpersand/data/remote/datasource/court/CourtDataSource.kt
  data/src/main/java/com/mpersand/data/remote/datasource/court/CourtDataSourceImpl.kt
  data/src/test/java/com/mpersand/data/remote/datasource/court/CourtDataSourceTest.kt
  gradle/libs.versions.toml
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#126 🔀 :: (#125) write court domain logic
  data/src/main/java/com/mpersand/data/remote/model/court/response/CourtResponse.kt
  data/src/main/java/com/mpersand/data/remote/model/util/CourtType.kt
  data/src/main/java/com/mpersand/data/remote/model/util/DayOfWeekType.kt
  data/src/main/java/com/mpersand/data/remote/model/util/SportType.kt
  data/src/main/java/com/mpersand/data/repository/CourtRepositoryImpl.kt
  domain/build.gradle.kts
  domain/src/main/java/com/mpersand/domain/model/court/response/CourtResponseModel.kt
  domain/src/main/java/com/mpersand/domain/model/util/CourtTypeModel.kt
  domain/src/main/java/com/mpersand/domain/model/util/DayOfWeekTypeModel.kt
  domain/src/main/java/com/mpersand/domain/model/util/SportTypeModel.kt
  domain/src/main/java/com/mpersand/domain/repository/CourtRepository.kt
  domain/src/main/java/com/mpersand/domain/usecase/court/BanCourtByIdUseCase.kt
  domain/src/main/java/com/mpersand/domain/usecase/court/GetAllCourtsUseCase.kt
  domain/src/main/java/com/mpersand/domain/usecase/court/GetCourtByIdUseCase.kt
  domain/src/test/java/com/mpersand/domain/usecase/court/BanCourtByIdUseCaseTest.kt
  domain/src/test/java/com/mpersand/domain/usecase/court/GetAllCourtsUseCaseTest.kt
  domain/src/test/java/com/mpersand/domain/usecase/court/GetCourtByIdUseCaseTest.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#128 🔀 :: (#123) write notice viewmodel logic
  presentation/src/main/java/com/mpersand/presentation/viewmodel/notice/NoticeCreateViewModel.kt
  presentation/src/main/java/com/mpersand/presentation/viewmodel/notice/NoticeDetailViewModel.kt
  presentation/src/main/java/com/mpersand/presentation/viewmodel/notice/NoticeModifyViewModel.kt
  presentation/src/main/java/com/mpersand/presentation/viewmodel/notice/NoticeViewModel.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#129 🔀 :: (#127) write court viewmodel logic
  app/src/main/java/com/mpersand/gymi_android/module/RemoteDataSourceModule.kt
  app/src/main/java/com/mpersand/gymi_android/module/RepositoryModule.kt
  presentation/src/main/java/com/mpersand/presentation/viewmodel/ban/BanViewModel.kt
  presentation/src/main/java/com/mpersand/presentation/viewmodel/main/MainViewModel.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#131 🔀 :: (#130) zoned time not convent error
  data/src/main/java/com/mpersand/data/remote/model/auth/request/TokenReissueRequest.kt
  data/src/main/java/com/mpersand/data/remote/model/auth/response/GauthLoginResponse.kt
  data/src/main/java/com/mpersand/data/remote/util/RequestInterceptor.kt
  domain/src/main/java/com/mpersand/domain/model/auth/response/GauthLoginResponseModel.kt
  presentation/src/main/java/com/mpersand/presentation/viewmodel/auth/AuthViewModel.kt
Labels: 0️⃣ Priority: Critical, 🐞 Type: Bug

#133 🔀 :: (#132) write court reservation remote logic
  app/src/main/java/com/mpersand/gymi_android/module/NetworkModule.kt
  data/src/main/java/com/mpersand/data/remote/model/reservation/request/ReservationRequest.kt
  data/src/main/java/com/mpersand/data/remote/network/ReservationApi.kt
Labels: 📬 Type: API, ✨ Type: Feature

#135 🔀 :: (#134) write court reservation data logic
  app/src/main/java/com/mpersand/gymi_android/module/RemoteDataSourceModule.kt
  data/src/main/java/com/mpersand/data/remote/datasource/reservation/ReservationDataSource.kt
  data/src/main/java/com/mpersand/data/remote/datasource/reservation/ReservationDataSourceImpl.kt
  data/src/main/java/com/mpersand/data/remote/network/ReservationApi.kt
  data/src/test/java/com/mpersand/data/remote/datasource/reservation/ReservationDataSourceTest.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#137 🔀 :: (#136) write court reservation domain logic
  app/src/main/java/com/mpersand/gymi_android/module/RepositoryModule.kt
  data/src/main/java/com/mpersand/data/remote/model/reservation/request/ReservationRequest.kt
  data/src/main/java/com/mpersand/data/repository/ReservationRepositoryImpl.kt
  domain/src/main/java/com/mpersand/domain/model/reservation/request/ReservationRequestModel.kt
  domain/src/main/java/com/mpersand/domain/repository/ReservationRepository.kt
  domain/src/main/java/com/mpersand/domain/usecase/reservation/CancelReservationUseCase.kt
  domain/src/main/java/com/mpersand/domain/usecase/reservation/ReserveCourtUseCase.kt
  domain/src/test/java/com/mpersand/domain/usecase/reservation/CancelReservationUseCaseTest.kt
  domain/src/test/java/com/mpersand/domain/usecase/reservation/ReserveCourtUseCaseTest.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#139 🔀 :: (#138) write court reservation viewmodel logic
  presentation/src/main/java/com/mpersand/presentation/viewmodel/reservation/ReservationViewModel.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#141 🔀 :: (#140) connect court reservation to screen
  presentation/src/main/java/com/mpersand/presentation/view/component/BasketballHalfCourt.kt
  presentation/src/main/java/com/mpersand/presentation/view/reservation/ReservationScreen.kt
  presentation/src/main/java/com/mpersand/presentation/viewmodel/reservation/ReservationViewModel.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#143 🔀 :: (#142) connect to get all court to screen
  data/src/main/java/com/mpersand/data/remote/model/court/response/CourtResponse.kt
  data/src/test/java/com/mpersand/data/remote/datasource/court/CourtDataSourceTest.kt
  domain/src/main/java/com/mpersand/domain/model/court/response/CourtResponseModel.kt
  domain/src/test/java/com/mpersand/domain/usecase/court/GetAllCourtsUseCaseTest.kt
  domain/src/test/java/com/mpersand/domain/usecase/court/GetCourtByIdUseCaseTest.kt
  presentation/src/main/java/com/mpersand/presentation/view/component/BasketballHalfCourt.kt
  presentation/src/main/java/com/mpersand/presentation/view/reservation/ReservationScreen.kt
  presentation/src/main/java/com/mpersand/presentation/viewmodel/reservation/ReservationViewModel.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#145 🔀 :: (#144) connect cancel reservation dialog logic
  gradle/libs.versions.toml
  presentation/src/main/java/com/mpersand/presentation/view/component/BadmintonHalfCourt.kt
  presentation/src/main/java/com/mpersand/presentation/view/component/BasketballHalfCourt.kt
  presentation/src/main/java/com/mpersand/presentation/view/main/MainScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/reservation/ReservationScreen.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#147 🔀 :: (#146) reservation screen bug
  data/src/main/java/com/mpersand/data/remote/util/RequestInterceptor.kt
  presentation/src/main/java/com/mpersand/presentation/view/reservation/ReservationScreen.kt
Labels: 0️⃣ Priority: Critical, 🐞 Type: Bug
